version: "3.9"

services:
    db:
        # platform: linux/arm64
        image: arm64v8/mysql:oracle
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
        exposed:
            - 3306
        volumes:
            - ./data/db:/var/lib/mysql

    web:
        build: .
        command: python3 manage.py runserver
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
