
services:
    db:
        # platform: linux/arm64
        image: mysql/mysql-server
        restart: always
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: edt
            MYSQL_USER: edt        
        expose:
            - 3306
        volumes:
            - ./data/db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
            interval: 30s

    web:
        build: .
        command: python manage.py runserver 0.0.0.0:80
        volumes:
            - .:/code
        ports:
            - 80:80
        depends_on:
            db:
                condition: service_healthy
 