
services:

    web:
        build: .
        entrypoint: /entrypoint.sh
        command: ["python", "manage.py", "runserver", "0.0.0.0:80"]
        volumes:
            - .:/code
        restart: on-failure
        ports:
            - 80:80
      
   
        