name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    services:
      db:
       image: mysql/mysql-server
        env:
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: edt
            MYSQL_USER: edt        
        expose:
            - 3306
        volumes:
            - ./data/db:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: $
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: mysql
        DBUSER: root
        DBPASSWORD: root
        DBHOST: 127.0.0.1
        DBPORT: $
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: mysql
        DBUSER: root
        DBPASSWORD: root
        DBHOST: 127.0.0.1
        DBPORT: $
